### ISSUE TITLE
[number field] Bug when component is controlled

### ISSUE THREAD

**Issue by blinkofaneye** [mui/base-ui#163] opened 2024-03-07 12:56 UTC
### Steps to reproduce

Link to live example: [CodeSandbox](https://codesandbox.io/p/sandbox/vigilant-meadow-c7wqr5?file=%2Fsrc%2FDemo.tsx%3A37%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clth7pi5m00072v6h655vy83t%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clth7pi5l00032v6hnc107k7i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clth7pi5l00042v6haqri5tct%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clth7pi5l00062v6hbojbs1al%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clth7pi5l00032v6hnc107k7i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth7pi5l00022v6hg3trcxdj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A37%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A37%252C%2522endColumn%2522%253A11%257D%255D%257D%255D%252C%2522id%2522%253A%2522clth7pi5l00032v6hnc107k7i%2522%252C%2522activeTabId%2522%253A%2522clth7pi5l00022v6hg3trcxdj%2522%257D%252C%2522clth7pi5l00062v6hbojbs1al%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clth7pi5l00052v6h1jps68zm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clth7pi5l00062v6hbojbs1al%2522%252C%2522activeTabId%2522%253A%2522clth7pi5l00052v6h1jps68zm%2522%257D%252C%2522clth7pi5l00042v6haqri5tct%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clth7pi5l00042v6haqri5tct%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Steps:
1. make component controlled (value, onChange)
2.enter any number in the field (5 for example)
3.change value programmatically (2 for example)
4.set focus on the field (click on it)

![2024-03-07 15-46-23](https://github.com/mui/material-ui/assets/33689656/a56c2cee-aa20-44e2-9193-98099388c6e8)

### Current behavior

when the component is controlled, the value set programmatically is lost when you click on the input

### Expected behavior

when the component is controlled, the value set programmatically should not be lost

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 122.0.6261.111
  npmPackages:
    @emotion/react: ^11.11.3 => 11.11.3 
    @emotion/styled: ^11.11.0 => 11.11.0 
    @mui/base:  5.0.0-beta.32 
    @mui/core-downloads-tracker:  5.15.5 
    @mui/icons-material: ^5.15.5 => 5.15.5 
    @mui/material: ^5.15.5 => 5.15.5 
    @mui/private-theming:  5.15.5 
    @mui/styled-engine:  5.15.5 
    @mui/system:  5.15.5 
    @mui/types:  7.2.13 
    @mui/utils:  5.15.5 
    @mui/x-data-grid: ^6.19.1 => 6.19.1 
    @mui/x-date-pickers: ^6.19.2 => 6.19.2 
    @types/react: ^18.2.48 => 18.2.48 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    typescript: ^5.3.3 => 5.3.3
```
</details>

**Search keywords**: number input

**Search keywords**:

**Comment by oliviertassinari** [comment] 2024-03-22 00:07
@blinkofaneye It looks like you didn't save the codesandbox. Could you update the reproduction? Thanks

**Comment by michaldudak** [comment] 2024-04-12 09:35
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://mui.com/r/issue-template), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by oliviertassinari** [comment] 2024-05-24 11:30
I can reproduce https://codesandbox.io/p/sandbox/goofy-river-n7tm76?file=%2Fsrc%2FDemo.tsx. It's definitely broken. 

https://github.com/mui/base-ui/assets/3165635/fd571c8c-aa45-4660-85f0-0b26963ef4a3

I'm reopening. I guess closing this is only about making sure that the component that replaces it https://master--base-ui.netlify.app/base-ui/react-number-field/, doesn't have this bug.

**Comment by atomiks** [comment] 2024-05-28 04:47
I attempted to reproduce this issue with the new Number Field  in `v1.0.0-alpha.1`, but it doesn't occur: https://master--base-ui.netlify.app/base-ui/react-number-field/. 

Closing as it looks to be fixed.

**Closed by atomiks** 2024-05-28 04:47 UTC
Labels: component: number field, bug 🐛
